# Generated by Django 2.2 on 2021-01-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
