# Generated by Django 2.2 on 2021-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210123_1254'),
        ('accounts', '0005_delete_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default=None, to='webapp.Friend'),
        ),
    ]
