# Generated by Django 2.2 on 2021-01-23 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210123_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
