# Generated by Django 2.2 on 2021-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210123_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
