# Generated by Django 2.2 on 2021-01-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210123_1256'),
        ('webapp', '0009_auto_20210123_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
